### ISSUE TITLE
Missing files are not detected as not existing

### ISSUE THREAD

**Issue by username223** [spacemeowx2/blflash#2]
When running the latest version from the release page, `blflash 0.2.1`, non-existing files are not detected but instead lead to `Connection Succeed` followed by an `IO error while using serial port: Operation timed out` after some time.

Full log:
```bash
$ ./blflash-linux-amd64 flash does-not-exist.bin --port /dev/ttyUSB0
[INFO  blflash::flasher] Start connection...
[TRACE blflash::flasher] 5ms send count 55
[TRACE blflash::flasher] handshake sent elapsed 581.196µs
[INFO  blflash::flasher] Connection Succeed
Error: IO error while using serial port: Operation timed out
caused by: Operation timed out
$ ./blflash-linux-amd64 --version
blflash 0.2.1
```

**Comment by spacemeowx2** [comment]
It seems that your chip is running `eflash loader`, which can handshake without error but can't get bootrom version, and throwing `Operation timed out`. The flasher will open the file after getting bootrom info. so you got the timed out error first.

Indeed, for a better experience, the flasher should open the file first instead of opening the serial port.
